[project]
name = "tnfsh-timetable-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.18",
    "bs4>=0.0.2",
    "pydantic>=2.11.4",
    "pytest>=8.3.5",
    "requests>=2.32.3",
]
